deps: update to use rollkit v0.6.0
celestiaorg/ethermint pull request #83
Opened 2023-01-31 16:58 UTC by tzdybal

Closes: #XXX

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2023-01-31 20:32 UTC, jcstein approved these changes
Looks good to me. Thank you @tzdybal

2023-02-01 10:46 UTC, nashqueue requested changes

2023-02-01 10:46 UTC, nashqueue commented on testutil/network/network.go
>  				select {
Why are we removing those error messages?

2023-02-01 10:57 UTC, tzdybal commented on testutil/network/network.go
>  				select {
Because we don't have logger in Node interface, and this is only a test.

2023-02-01 10:58 UTC, nashqueue approved these changes

2023-02-01 20:30 UTC, jcstein commented
Testing rollkit installation was successful on this branch:

- [ ] [installation of ethermintd](https://app.warp.dev/block/Xxr4TU63TpPXOpSMtVFPD6) & [running `ethermintd`](https://app.warp.dev/block/9YkelD1IQ7getL2uYtXU8u)
- [ ] [set namespaceid and block height](https://app.warp.dev/block/pC0jXyZtEOPja5tJXIQx7O)
- [ ] [`bash init.sh`](https://app.warp.dev/block/DzPxt6m53LKdKF5iROTmPU)
- [ ] [running the chain connected to mocha node](https://app.warp.dev/block/3U7NkCBMXE9BrJcZaukjb3) 
- [ ] [wallet balance 100000 utia](https://app.warp.dev/block/oJamurmUzar7JO4pkFCNdk) -> [964000](https://app.warp.dev/block/4a9jwhTJeLzA75wzdwiyRg)

2023-02-01 20:35 UTC, merged